version: '3.9'

services:
  db:
    container_name: database_mariadb
    build:
      context: ./docker/mariadb
      dockerfile: dockerfile
    restart: always
    volumes:
      - volumePersistent:/var/lib/mysql
    env_file: # apenas para facilitar
      - .env
    networks:
      - desafio_network

  application:
    container_name: crud
    build: 
      context: .
      dockerfile: docker/php/dockerfile
    ports: # porta dinamica
      - '$PORT_HTTP:80'
    env_file:
      - .env
    volumes:
      - ./app/:/var/www/html
    depends_on:
      - db
    networks: 
      - desafio_network

networks:
  desafio_network:

volumes:
  volumePersistent: